# Site settings
title: KIT-10 Distract-O-Matic
email: stuart.feichtinger@gmail.com
description: Arduino-based laser turret/automatic cat toy

timezone: America/Chicago

# Build settings
baseurl: "Arduino-Laser-Cat-Turret"
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      GitHubUserName: "stuthedew"
      GitHubProjectName: "Arduino-Laser-Cat-Turret"
